ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE budgets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);